services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
    networks:
      - gabriel1_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/backups:/var/lib/postgresql/backups/
    env_file:
      - ./dotenv_files/.env
    networks:
      - gabriel1_net
    ports:
      - "54320:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - gabriel1_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  nginxconf:
    image: nginx:latest
    container_name: nginxconf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles/
      - ./data/web/media:/data/web/media/
      - ./certbot/conf:/etc/letsencrypt   # <--- certificados aqui
      - ./certbot/www:/var/www/certbot     # <--- validação do certbot aqui
      - /dev/null:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - djangoapp
    networks:
      - gabriel1_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginxconf
    networks:
      - gabriel1_net
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done"

networks:
  gabriel1_net:
    driver: bridge
