version: '3.8'

services:
  chanelbi_djangoapp:
    container_name: chanelbi_djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - chanelbi_psql
      - chanelbi_redis
    networks:
      - chanelbi_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  chanelbi_psql:
    container_name: chanelbi_psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/backups:/var/lib/postgresql/backups/
    env_file:
      - ./dotenv_files/.env
    ports:
      - "54320:5432"
    networks:
      - chanelbi_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  chanelbi_redis:
    container_name: chanelbi_redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - chanelbi_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  chanelbi_nginx:
    container_name: chanelbi_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/web/static:/data/web/static/
      - ./data/web/staticfiles:/data/web/staticfiles/
      - ./data/web/media:/data/web/media/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /dev/null:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chanelbi_djangoapp
    networks:
      - chanelbi_net

  chanelbi_certbot:
    container_name: chanelbi_certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - chanelbi_nginx
    networks:
      - chanelbi_net
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done"

networks:
  chanelbi_net:
    driver: bridge
