# Generated by Django 5.0.1 on 2025-03-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentdeslike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDeslike',
        ),
    ]
