# Generated by Django 5.0.1 on 2025-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='campanha/')),
                ('posicao', models.IntegerField(default=1)),
            ],
        ),
    ]
