# Generated by Django 5.0.1 on 2025-03-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0002_homebannerinicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebannerinicio',
            name='dtmov',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
