# Generated by Django 5.0.1 on 2025-03-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0003_homebannerinicio_dtmov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebannerinicio',
            name='dtmov',
        ),
    ]
