# Generated by Django 5.0.1 on 2025-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0004_remove_homebannerinicio_dtmov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerinicio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='home/banner/'),
        ),
    ]
