# Generated by Django 5.0.1 on 2025-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0007_falecomigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMinhaHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='home/minhahist/')),
                ('link', models.CharField(max_length=250)),
                ('descricao', models.TextField(max_length=1500)),
            ],
        ),
    ]
