# Generated by Django 5.0.1 on 2025-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0008_homeminhahistoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeminhahistoria',
            name='descricao',
            field=models.TextField(max_length=4000),
        ),
    ]
