# Generated by Django 5.0.1 on 2025-03-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0009_alter_homeminhahistoria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemcampanha', models.ImageField(upload_to='home/minhahist/')),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
