# Generated by Django 5.0.1 on 2025-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0010_homebannercampanha'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='home/minhahist/')),
            ],
        ),
    ]
