# Generated by Django 5.0.1 on 2025-04-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0011_meuslinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meuslinks',
            name='nome',
        ),
    ]
