# Generated by Django 5.0.1 on 2025-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0012_remove_meuslinks_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='falecomigo',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='falecomigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fala_comigo/'),
        ),
        migrations.AddField(
            model_name='falecomigo',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
