# Generated by Django 5.0.1 on 2025-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0013_falecomigo_endereco_falecomigo_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falecomigo',
            name='descricao',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='falecomigo',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='falecomigo',
            name='endereco',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='falecomigo',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='falecomigo',
            name='telefone',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
