# Generated by Django 5.0.1 on 2025-04-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0014_alter_falecomigo_descricao_alter_falecomigo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falecomigo',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='falecomigo',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
