# Generated by Django 5.0.1 on 2025-04-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusables', '0015_alter_falecomigo_endereco_alter_falecomigo_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuslinks',
            name='location_link',
            field=models.CharField(default='fagnerhome'),
        ),
    ]
