# Generated by Django 5.0.1 on 2025-04-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(max_length=15, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('primeiro_curso', models.CharField(choices=[('Informática Básica', 'Informática Básica'), ('Atendimento ao Cliente e Vendas', 'Atendimento ao Cliente e Vendas'), ('Comunicação Eficiente', 'Comunicação Eficiente'), ('Gestão de Tempo e Produtividade', 'Gestão de Tempo e Produtividade'), ('Empreendedorismo Social', 'Empreendedorismo Social'), ('Como se Destacar no Mercado de Trabalho', 'Como se Destacar no Mercado de Trabalho'), ('Marketing digital', 'Marketing digital')], max_length=100, verbose_name='1º Curso Desejado')),
                ('segundo_curso', models.CharField(choices=[('Informática Básica', 'Informática Básica'), ('Atendimento ao Cliente e Vendas', 'Atendimento ao Cliente e Vendas'), ('Comunicação Eficiente', 'Comunicação Eficiente'), ('Gestão de Tempo e Produtividade', 'Gestão de Tempo e Produtividade'), ('Empreendedorismo Social', 'Empreendedorismo Social'), ('Como se Destacar no Mercado de Trabalho', 'Como se Destacar no Mercado de Trabalho'), ('Marketing digital', 'Marketing digital')], max_length=100, verbose_name='2º Curso Desejado')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros')], max_length=20, verbose_name='Sexo')),
                ('funcionario_terceirizado', models.BooleanField(verbose_name='É Funcionário Terceirizado?')),
                ('filho_funcionario_terceirizado', models.BooleanField(verbose_name='É Filho de Funcionário Terceirizado?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
